name:                fpday2021
version:             0.1.0.0
github:              "nobsun/fpday2021"
license:             BSD3
author:              "Nobuo Yamashita"
maintainer:          "nobsun@sampou.org"
copyright:           "Copyright: (c) 2021 Nobuo Yamashita"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Experiment

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/nobsun/fpday2021#readme>

dependencies:
- base >= 4.7 && < 5
- unicode-show
- bytestring
- utf8-string
- time
- array

library:
  source-dirs: src

executables:
  toysim:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -rtsopts
    # - -threaded
    # - -with-rtsopts=-N
    dependencies:
    - fpday2021

  # toysim2:
  #   main:                toysim2.hs
  #   source-dirs:         app
  #   ghc-options:
  #   - -rtsopts
  #   # - -threaded
  #   # - -with-rtsopts=-N
  #   dependencies:
  #   - fpday2021

  # toysim3:
  #   main:                toysim3.hs
  #   source-dirs:         app
  #   ghc-options:
  #   - -rtsopts
  #   # - -threaded
  #   # - -with-rtsopts=-N
  #   dependencies:
  #   - fpday2021

tests:
  fpday2021-test:
    main:                spec.hs
    source-dirs:         test
    # ghc-options:
    # - -threaded
    # - -rtsopts
    # - -with-rtsopts=-N
    dependencies:
    - fpday2021
    - hspec
    - main-tester

  fpday2021-doctest:
    main:                doctests.hs
    source-dirs:         test
    # ghc-options:
    # - -threaded
    # - -rtsopts
    # - -with-rtsopts=-N
    dependencies:
    - fpday2021
    - doctest
